### ISSUE TITLE
Unable to save video recordings

### ISSUE THREAD

**Issue by mikepowell** [mattbierner/face-drop-support#1]
This app is hilarious but sadly I've been unable to save or share videos to other apps using the share sheet. I don't see an error message, there's just nothing added to my camera roll. If I share to another app the other app comes up with no attachment (e.g. Twitter, Discord), or a 0-byte file (Gmail). Photos seem to work fine. Any suggestions on what I can check?

**Comment by mattbierner** [comment]
Thanks for the report! I just submitted a fix. It should be out once it passes App Store review

**Comment by mikepowell** [comment]
My kids and I will look forward to it, thank you!

**Comment by mikepowell** [comment]
I just found it has already updated and works great, thanks!
